FROM node:20.19.2 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --include=dev
COPY . .
ARG NODE_ENV=development
RUN npm run build:${NODE_ENV}

FROM nginx:alpine
WORKDIR /app
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 7942